# Generated by Django 2.1.5 on 2019-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph', models.CharField(max_length=12)),
                ('clg', models.CharField(max_length=30)),
                ('clgid', models.CharField(blank=True, max_length=15)),
                ('aad', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('prize', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField(blank=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
