# Generated by Django 2.1.5 on 2019-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('prize', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='intraEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('prize', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
