# Generated by Django 2.1.5 on 2019-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('prize', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='interEvents',
        ),
        migrations.DeleteModel(
            name='intraEvents',
        ),
    ]
